{
  imports = [
    ./compatibility.nix
    ./docker.nix
    ./fish.nix
    ./flatpak.nix
    ./fonts.nix
    ./fs.nix
    ./gamemode.nix
    ./gtk.nix
    ./hardware.nix
    ./location.nix
    ./mullvad.nix
    ./networking.nix
    ./pipewire.nix
    ./plasma.nix
    ./printing.nix
    ./syncthing.nix
    ./vscode.nix
  ];
}
