{
  imports = [
    ./clipboard.nix
    ./docker.nix
    ./flatpak.nix
    ./fonts.nix
    ./fs.nix
    ./gamemode.nix
    ./hardware.nix
    ./location.nix
    ./mullvad.nix
    ./neovide.nix
    ./networking.nix
    ./pipewire.nix
    ./plasma.nix
    ./printing.nix
    ./syncthing.nix
    ./users.nix
    ./vm.nix
    ./wine.nix
  ];
}
